version: '3.5'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgres/data
    ports:
      - "5432:5432"
    restart: always
volumes:
  db: